site_name: LightJAS

# Documentation and theme
theme:
    name: 'material'

markdown_extensions:
    - admonition
    - codehilite

pages:
    - Home: index.md
    - Spec: spec.md
    - Tagset:
        - table: table.md
        - figure: figure.md